### ISSUE TITLE
What is "totalDeepSeqTagCountsPerCelltype.txt"?

### ISSUE THREAD

**Issue by Puriney** [Altius/correlatedDHS#1]
I was wondering what is inside "totalDeepSeqTagCountsPerCelltype.txt" since it is ignored to be uploaded (see [.gitignore](https://github.com/Altius/correlatedDHS/blob/67a6ce90e491fe7fb43ee5eb0c0286615f835b35/.gitignore#L9)) while still remained in source codes (see [here](https://github.com/Altius/correlatedDHS/blob/67a6ce90e491fe7fb43ee5eb0c0286615f835b35/makeMasterFileWithTagSumVectors.sh#L9) in `makeMasterFileWithTagSumVectors`).

`TT=totalDeepSeqTagCountsPerCelltype.txt`
- what is the content? Based on src code [here](https://github.com/Altius/correlatedDHS/blob/67a6ce90e491fe7fb43ee5eb0c0286615f835b35/makeMasterFileWithTagSumVectors.sh#L99) I would guess it is like

```
celltype1 \t TotalTagsNum
celltype2 \t TotalTagsNum
```
- what is the format, like BED?
- could you upload it so that you can keep the repo running reproducible.

**Comment by fwip** [comment]
Sorry about that, I'll get that file uploaded.

It's a tab-separated file that contains the name of the celltype along with the number of tags that were used to generate the density file - it's used for normalization. The format is:
`A549-DS14289    221981518
AG10803-DS12374 227694445
AoAF-DS13513    323805977
CD14-DS16508    268397637
CD14-DS17215    383751451
CD19-DS17186    480773397
CD20-DS18208    236887485
CD34-DS12274    215790940
...`

**Comment by Puriney** [comment]
This is a follow-up question: what is the maximum number within this file? 

I cannot check the details as only the file link is contained in your commit https://github.com/Altius/correlatedDHS/commit/3d64115f4e0f42db751e21599f266a2bf3f85bbd

**Comment by fwip** [comment]
Apologies, I've fixed the symlink issue: https://github.com/Altius/correlatedDHS/blob/master/totalDeepSeqTagCountsPerCelltype.txt
